# docker-compose-test.yml
version: '3'
services:
  db:
    image: postgres:13.4-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: didomidb-test
    ports:
      - '5432:5432'
  app:
    build: .
    environment:
      NODE_ENV: test
      TYPEORM_DATABASE: didomidb-test
      TYPEORM_HOST: db
    depends_on:
      - db
    ports:
      - '3000:3000'
