# docker-compose.yml
version: '3'
services:
  db:
    image: postgres:13.4-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: didomidb
    ports:
      - '5432:5432'
  app:
    build: .
    depends_on:
      - db
    ports:
      - '3000:3000'
